-- Stable wrapper functions for indexer stored procedures.
-- Auto-generated by local script; adjust manually if needed.

CREATE OR REPLACE FUNCTION deployment_init(
    actor_user_public_id UUID
)
RETURNS VOID
LANGUAGE plpgsql
AS $$
BEGIN
    PERFORM deployment_init_v1(actor_user_public_id => actor_user_public_id);
END;
$$;

CREATE OR REPLACE FUNCTION app_user_create(
    email_input VARCHAR,
    display_name_input VARCHAR
)
RETURNS UUID
LANGUAGE sql
AS $$
    SELECT app_user_create_v1(email_input => email_input, display_name_input => display_name_input);
$$;

CREATE OR REPLACE FUNCTION app_user_update(
    user_public_id_input UUID,
    display_name_input VARCHAR
)
RETURNS VOID
LANGUAGE plpgsql
AS $$
BEGIN
    PERFORM app_user_update_v1(user_public_id_input => user_public_id_input, display_name_input => display_name_input);
END;
$$;

CREATE OR REPLACE FUNCTION app_user_verify_email(
    user_public_id_input UUID
)
RETURNS VOID
LANGUAGE plpgsql
AS $$
BEGIN
    PERFORM app_user_verify_email_v1(user_public_id_input => user_public_id_input);
END;
$$;

CREATE OR REPLACE FUNCTION tag_create(
    actor_user_public_id UUID,
    tag_key_input VARCHAR,
    display_name_input VARCHAR
)
RETURNS UUID
LANGUAGE sql
AS $$
    SELECT tag_create_v1(actor_user_public_id => actor_user_public_id, tag_key_input => tag_key_input, display_name_input => display_name_input);
$$;

CREATE OR REPLACE FUNCTION tag_update(
    actor_user_public_id UUID,
    tag_public_id_input UUID,
    tag_key_input VARCHAR,
    display_name_input VARCHAR
)
RETURNS UUID
LANGUAGE sql
AS $$
    SELECT tag_update_v1(actor_user_public_id => actor_user_public_id, tag_public_id_input => tag_public_id_input, tag_key_input => tag_key_input, display_name_input => display_name_input);
$$;

CREATE OR REPLACE FUNCTION tag_soft_delete(
    actor_user_public_id UUID,
    tag_public_id_input UUID,
    tag_key_input VARCHAR
)
RETURNS VOID
LANGUAGE plpgsql
AS $$
BEGIN
    PERFORM tag_soft_delete_v1(actor_user_public_id => actor_user_public_id, tag_public_id_input => tag_public_id_input, tag_key_input => tag_key_input);
END;
$$;

CREATE OR REPLACE FUNCTION routing_policy_create(
    actor_user_public_id UUID,
    display_name_input VARCHAR,
    mode_input routing_policy_mode
)
RETURNS UUID
LANGUAGE sql
AS $$
    SELECT routing_policy_create_v1(actor_user_public_id => actor_user_public_id, display_name_input => display_name_input, mode_input => mode_input);
$$;

CREATE OR REPLACE FUNCTION routing_policy_set_param(
    actor_user_public_id UUID,
    routing_policy_public_id_input UUID,
    param_key_input routing_param_key,
    value_plain_input VARCHAR,
    value_int_input INTEGER,
    value_bool_input BOOLEAN
)
RETURNS VOID
LANGUAGE plpgsql
AS $$
BEGIN
    PERFORM routing_policy_set_param_v1(actor_user_public_id => actor_user_public_id, routing_policy_public_id_input => routing_policy_public_id_input, param_key_input => param_key_input, value_plain_input => value_plain_input, value_int_input => value_int_input, value_bool_input => value_bool_input);
END;
$$;

CREATE OR REPLACE FUNCTION routing_policy_bind_secret(
    actor_user_public_id UUID,
    routing_policy_public_id_input UUID,
    param_key_input routing_param_key,
    secret_public_id_input UUID
)
RETURNS VOID
LANGUAGE plpgsql
AS $$
BEGIN
    PERFORM routing_policy_bind_secret_v1(actor_user_public_id => actor_user_public_id, routing_policy_public_id_input => routing_policy_public_id_input, param_key_input => param_key_input, secret_public_id_input => secret_public_id_input);
END;
$$;

CREATE OR REPLACE FUNCTION indexer_cf_state_reset(
    actor_user_public_id UUID,
    indexer_instance_public_id_input UUID,
    reason_input VARCHAR
)
RETURNS VOID
LANGUAGE plpgsql
AS $$
BEGIN
    PERFORM indexer_cf_state_reset_v1(actor_user_public_id => actor_user_public_id, indexer_instance_public_id_input => indexer_instance_public_id_input, reason_input => reason_input);
END;
$$;

CREATE OR REPLACE FUNCTION rate_limit_policy_create(
    actor_user_public_id UUID,
    display_name_input VARCHAR,
    rpm_input INTEGER,
    burst_input INTEGER,
    concurrent_input INTEGER
)
RETURNS UUID
LANGUAGE sql
AS $$
    SELECT rate_limit_policy_create_v1(actor_user_public_id => actor_user_public_id, display_name_input => display_name_input, rpm_input => rpm_input, burst_input => burst_input, concurrent_input => concurrent_input);
$$;

CREATE OR REPLACE FUNCTION rate_limit_policy_update(
    actor_user_public_id UUID,
    rate_limit_policy_public_id_input UUID,
    display_name_input VARCHAR,
    rpm_input INTEGER,
    burst_input INTEGER,
    concurrent_input INTEGER
)
RETURNS VOID
LANGUAGE plpgsql
AS $$
BEGIN
    PERFORM rate_limit_policy_update_v1(actor_user_public_id => actor_user_public_id, rate_limit_policy_public_id_input => rate_limit_policy_public_id_input, display_name_input => display_name_input, rpm_input => rpm_input, burst_input => burst_input, concurrent_input => concurrent_input);
END;
$$;

CREATE OR REPLACE FUNCTION rate_limit_policy_soft_delete(
    actor_user_public_id UUID,
    rate_limit_policy_public_id_input UUID
)
RETURNS VOID
LANGUAGE plpgsql
AS $$
BEGIN
    PERFORM rate_limit_policy_soft_delete_v1(actor_user_public_id => actor_user_public_id, rate_limit_policy_public_id_input => rate_limit_policy_public_id_input);
END;
$$;

CREATE OR REPLACE FUNCTION indexer_instance_set_rate_limit_policy(
    actor_user_public_id UUID,
    indexer_instance_public_id_input UUID,
    rate_limit_policy_public_id_input UUID
)
RETURNS VOID
LANGUAGE plpgsql
AS $$
BEGIN
    PERFORM indexer_instance_set_rate_limit_policy_v1(actor_user_public_id => actor_user_public_id, indexer_instance_public_id_input => indexer_instance_public_id_input, rate_limit_policy_public_id_input => rate_limit_policy_public_id_input);
END;
$$;

CREATE OR REPLACE FUNCTION routing_policy_set_rate_limit_policy(
    actor_user_public_id UUID,
    routing_policy_public_id_input UUID,
    rate_limit_policy_public_id_input UUID
)
RETURNS VOID
LANGUAGE plpgsql
AS $$
BEGIN
    PERFORM routing_policy_set_rate_limit_policy_v1(actor_user_public_id => actor_user_public_id, routing_policy_public_id_input => routing_policy_public_id_input, rate_limit_policy_public_id_input => rate_limit_policy_public_id_input);
END;
$$;

CREATE OR REPLACE FUNCTION rate_limit_try_consume(
    scope_type_input rate_limit_scope,
    scope_id_input BIGINT,
    capacity_input INTEGER,
    tokens_input INTEGER DEFAULT 1
)
RETURNS TABLE(allowed BOOLEAN, tokens_used INTEGER)
LANGUAGE sql
AS $$
    SELECT * FROM rate_limit_try_consume_v1(scope_type_input => scope_type_input, scope_id_input => scope_id_input, capacity_input => capacity_input, tokens_input => tokens_input);
$$;

CREATE OR REPLACE FUNCTION indexer_instance_create(
    actor_user_public_id UUID,
    indexer_definition_id_input BIGINT,
    display_name_input VARCHAR,
    priority_input INTEGER,
    trust_tier_key_input trust_tier_key,
    routing_policy_public_id_input UUID
)
RETURNS UUID
LANGUAGE sql
AS $$
    SELECT indexer_instance_create_v1(actor_user_public_id => actor_user_public_id, indexer_definition_id_input => indexer_definition_id_input, display_name_input => display_name_input, priority_input => priority_input, trust_tier_key_input => trust_tier_key_input, routing_policy_public_id_input => routing_policy_public_id_input);
$$;

CREATE OR REPLACE FUNCTION indexer_instance_update(
    actor_user_public_id UUID,
    indexer_instance_public_id_input UUID,
    display_name_input VARCHAR,
    priority_input INTEGER,
    trust_tier_key_input trust_tier_key,
    routing_policy_public_id_input UUID,
    is_enabled_input BOOLEAN,
    enable_rss_input BOOLEAN,
    enable_automatic_search_input BOOLEAN,
    enable_interactive_search_input BOOLEAN
)
RETURNS UUID
LANGUAGE sql
AS $$
    SELECT indexer_instance_update_v1(actor_user_public_id => actor_user_public_id, indexer_instance_public_id_input => indexer_instance_public_id_input, display_name_input => display_name_input, priority_input => priority_input, trust_tier_key_input => trust_tier_key_input, routing_policy_public_id_input => routing_policy_public_id_input, is_enabled_input => is_enabled_input, enable_rss_input => enable_rss_input, enable_automatic_search_input => enable_automatic_search_input, enable_interactive_search_input => enable_interactive_search_input);
$$;

CREATE OR REPLACE FUNCTION indexer_rss_subscription_set(
    actor_user_public_id UUID,
    indexer_instance_public_id_input UUID,
    is_enabled_input BOOLEAN,
    interval_seconds_input INTEGER
)
RETURNS VOID
LANGUAGE plpgsql
AS $$
BEGIN
    PERFORM indexer_rss_subscription_set_v1(actor_user_public_id => actor_user_public_id, indexer_instance_public_id_input => indexer_instance_public_id_input, is_enabled_input => is_enabled_input, interval_seconds_input => interval_seconds_input);
END;
$$;

CREATE OR REPLACE FUNCTION indexer_rss_subscription_disable(
    actor_user_public_id UUID,
    indexer_instance_public_id_input UUID
)
RETURNS VOID
LANGUAGE plpgsql
AS $$
BEGIN
    PERFORM indexer_rss_subscription_disable_v1(actor_user_public_id => actor_user_public_id, indexer_instance_public_id_input => indexer_instance_public_id_input);
END;
$$;

CREATE OR REPLACE FUNCTION indexer_instance_set_media_domains(
    actor_user_public_id UUID,
    indexer_instance_public_id_input UUID,
    media_domain_keys_input TEXT[]
)
RETURNS VOID
LANGUAGE plpgsql
AS $$
BEGIN
    PERFORM indexer_instance_set_media_domains_v1(actor_user_public_id => actor_user_public_id, indexer_instance_public_id_input => indexer_instance_public_id_input, media_domain_keys_input => media_domain_keys_input);
END;
$$;

CREATE OR REPLACE FUNCTION indexer_instance_set_tags(
    actor_user_public_id UUID,
    indexer_instance_public_id_input UUID,
    tag_public_ids_input UUID[],
    tag_keys_input TEXT[]
)
RETURNS VOID
LANGUAGE plpgsql
AS $$
BEGIN
    PERFORM indexer_instance_set_tags_v1(actor_user_public_id => actor_user_public_id, indexer_instance_public_id_input => indexer_instance_public_id_input, tag_public_ids_input => tag_public_ids_input, tag_keys_input => tag_keys_input);
END;
$$;

CREATE OR REPLACE FUNCTION indexer_instance_field_set_value(
    actor_user_public_id UUID,
    indexer_instance_public_id_input UUID,
    field_name_input VARCHAR,
    value_plain_input VARCHAR,
    value_int_input INTEGER,
    value_decimal_input NUMERIC,
    value_bool_input BOOLEAN
)
RETURNS VOID
LANGUAGE plpgsql
AS $$
BEGIN
    PERFORM indexer_instance_field_set_value_v1(actor_user_public_id => actor_user_public_id, indexer_instance_public_id_input => indexer_instance_public_id_input, field_name_input => field_name_input, value_plain_input => value_plain_input, value_int_input => value_int_input, value_decimal_input => value_decimal_input, value_bool_input => value_bool_input);
END;
$$;

CREATE OR REPLACE FUNCTION indexer_instance_field_bind_secret(
    actor_user_public_id UUID,
    indexer_instance_public_id_input UUID,
    field_name_input VARCHAR,
    secret_public_id_input UUID
)
RETURNS VOID
LANGUAGE plpgsql
AS $$
BEGIN
    PERFORM indexer_instance_field_bind_secret_v1(actor_user_public_id => actor_user_public_id, indexer_instance_public_id_input => indexer_instance_public_id_input, field_name_input => field_name_input, secret_public_id_input => secret_public_id_input);
END;
$$;

CREATE OR REPLACE FUNCTION tracker_category_mapping_upsert(
    actor_user_public_id UUID,
    indexer_definition_upstream_slug_input VARCHAR,
    tracker_category_input INTEGER,
    tracker_subcategory_input INTEGER,
    torznab_cat_id_input INTEGER,
    media_domain_key_input VARCHAR
)
RETURNS VOID
LANGUAGE plpgsql
AS $$
BEGIN
    PERFORM tracker_category_mapping_upsert_v1(actor_user_public_id => actor_user_public_id, indexer_definition_upstream_slug_input => indexer_definition_upstream_slug_input, tracker_category_input => tracker_category_input, tracker_subcategory_input => tracker_subcategory_input, torznab_cat_id_input => torznab_cat_id_input, media_domain_key_input => media_domain_key_input);
END;
$$;

CREATE OR REPLACE FUNCTION tracker_category_mapping_delete(
    actor_user_public_id UUID,
    indexer_definition_upstream_slug_input VARCHAR,
    tracker_category_input INTEGER,
    tracker_subcategory_input INTEGER
)
RETURNS VOID
LANGUAGE plpgsql
AS $$
BEGIN
    PERFORM tracker_category_mapping_delete_v1(actor_user_public_id => actor_user_public_id, indexer_definition_upstream_slug_input => indexer_definition_upstream_slug_input, tracker_category_input => tracker_category_input, tracker_subcategory_input => tracker_subcategory_input);
END;
$$;

CREATE OR REPLACE FUNCTION media_domain_to_torznab_category_upsert(
    actor_user_public_id UUID,
    media_domain_key_input VARCHAR,
    torznab_cat_id_input INTEGER,
    is_primary_input BOOLEAN
)
RETURNS VOID
LANGUAGE plpgsql
AS $$
BEGIN
    PERFORM media_domain_to_torznab_category_upsert_v1(actor_user_public_id => actor_user_public_id, media_domain_key_input => media_domain_key_input, torznab_cat_id_input => torznab_cat_id_input, is_primary_input => is_primary_input);
END;
$$;

CREATE OR REPLACE FUNCTION media_domain_to_torznab_category_delete(
    actor_user_public_id UUID,
    media_domain_key_input VARCHAR,
    torznab_cat_id_input INTEGER
)
RETURNS VOID
LANGUAGE plpgsql
AS $$
BEGIN
    PERFORM media_domain_to_torznab_category_delete_v1(actor_user_public_id => actor_user_public_id, media_domain_key_input => media_domain_key_input, torznab_cat_id_input => torznab_cat_id_input);
END;
$$;

CREATE OR REPLACE FUNCTION policy_set_create(
    actor_user_public_id UUID,
    display_name_input VARCHAR,
    scope_input policy_scope,
    enabled_input BOOLEAN
)
RETURNS UUID
LANGUAGE sql
AS $$
    SELECT policy_set_create_v1(actor_user_public_id => actor_user_public_id, display_name_input => display_name_input, scope_input => scope_input, enabled_input => enabled_input);
$$;

CREATE OR REPLACE FUNCTION policy_set_update(
    actor_user_public_id UUID,
    policy_set_public_id_input UUID,
    display_name_input VARCHAR
)
RETURNS UUID
LANGUAGE sql
AS $$
    SELECT policy_set_update_v1(actor_user_public_id => actor_user_public_id, policy_set_public_id_input => policy_set_public_id_input, display_name_input => display_name_input);
$$;

CREATE OR REPLACE FUNCTION policy_set_enable(
    actor_user_public_id UUID,
    policy_set_public_id_input UUID
)
RETURNS VOID
LANGUAGE plpgsql
AS $$
BEGIN
    PERFORM policy_set_enable_v1(actor_user_public_id => actor_user_public_id, policy_set_public_id_input => policy_set_public_id_input);
END;
$$;

CREATE OR REPLACE FUNCTION policy_set_disable(
    actor_user_public_id UUID,
    policy_set_public_id_input UUID
)
RETURNS VOID
LANGUAGE plpgsql
AS $$
BEGIN
    PERFORM policy_set_disable_v1(actor_user_public_id => actor_user_public_id, policy_set_public_id_input => policy_set_public_id_input);
END;
$$;

CREATE OR REPLACE FUNCTION policy_set_reorder(
    actor_user_public_id UUID,
    ordered_policy_set_public_ids UUID[]
)
RETURNS VOID
LANGUAGE plpgsql
AS $$
BEGIN
    PERFORM policy_set_reorder_v1(actor_user_public_id => actor_user_public_id, ordered_policy_set_public_ids => ordered_policy_set_public_ids);
END;
$$;

CREATE OR REPLACE FUNCTION policy_rule_disable(
    actor_user_public_id UUID,
    policy_rule_public_id_input UUID
)
RETURNS VOID
LANGUAGE plpgsql
AS $$
BEGIN
    PERFORM policy_rule_disable_v1(actor_user_public_id => actor_user_public_id, policy_rule_public_id_input => policy_rule_public_id_input);
END;
$$;

CREATE OR REPLACE FUNCTION policy_rule_enable(
    actor_user_public_id UUID,
    policy_rule_public_id_input UUID
)
RETURNS VOID
LANGUAGE plpgsql
AS $$
BEGIN
    PERFORM policy_rule_enable_v1(actor_user_public_id => actor_user_public_id, policy_rule_public_id_input => policy_rule_public_id_input);
END;
$$;

CREATE OR REPLACE FUNCTION policy_rule_reorder(
    actor_user_public_id UUID,
    policy_set_public_id_input UUID,
    ordered_rule_public_ids UUID[]
)
RETURNS VOID
LANGUAGE plpgsql
AS $$
BEGIN
    PERFORM policy_rule_reorder_v1(actor_user_public_id => actor_user_public_id, policy_set_public_id_input => policy_set_public_id_input, ordered_rule_public_ids => ordered_rule_public_ids);
END;
$$;

CREATE OR REPLACE FUNCTION search_profile_create(
    actor_user_public_id UUID,
    display_name_input VARCHAR,
    is_default_input BOOLEAN,
    page_size_input INTEGER,
    default_media_domain_key_input VARCHAR,
    user_public_id_input UUID
)
RETURNS UUID
LANGUAGE sql
AS $$
    SELECT search_profile_create_v1(actor_user_public_id => actor_user_public_id, display_name_input => display_name_input, is_default_input => is_default_input, page_size_input => page_size_input, default_media_domain_key_input => default_media_domain_key_input, user_public_id_input => user_public_id_input);
$$;

CREATE OR REPLACE FUNCTION search_profile_update(
    actor_user_public_id UUID,
    search_profile_public_id_input UUID,
    display_name_input VARCHAR,
    page_size_input INTEGER
)
RETURNS UUID
LANGUAGE sql
AS $$
    SELECT search_profile_update_v1(actor_user_public_id => actor_user_public_id, search_profile_public_id_input => search_profile_public_id_input, display_name_input => display_name_input, page_size_input => page_size_input);
$$;

CREATE OR REPLACE FUNCTION search_profile_set_default(
    actor_user_public_id UUID,
    search_profile_public_id_input UUID,
    page_size_input INTEGER
)
RETURNS VOID
LANGUAGE plpgsql
AS $$
BEGIN
    PERFORM search_profile_set_default_v1(actor_user_public_id => actor_user_public_id, search_profile_public_id_input => search_profile_public_id_input, page_size_input => page_size_input);
END;
$$;

CREATE OR REPLACE FUNCTION search_profile_set_default_domain(
    actor_user_public_id UUID,
    search_profile_public_id_input UUID,
    default_media_domain_key_input VARCHAR
)
RETURNS VOID
LANGUAGE plpgsql
AS $$
BEGIN
    PERFORM search_profile_set_default_domain_v1(actor_user_public_id => actor_user_public_id, search_profile_public_id_input => search_profile_public_id_input, default_media_domain_key_input => default_media_domain_key_input);
END;
$$;

CREATE OR REPLACE FUNCTION search_profile_set_domain_allowlist(
    actor_user_public_id UUID,
    search_profile_public_id_input UUID,
    media_domain_keys_input TEXT[]
)
RETURNS VOID
LANGUAGE plpgsql
AS $$
BEGIN
    PERFORM search_profile_set_domain_allowlist_v1(actor_user_public_id => actor_user_public_id, search_profile_public_id_input => search_profile_public_id_input, media_domain_keys_input => media_domain_keys_input);
END;
$$;

CREATE OR REPLACE FUNCTION search_profile_add_policy_set(
    actor_user_public_id UUID,
    search_profile_public_id_input UUID,
    policy_set_public_id_input UUID
)
RETURNS VOID
LANGUAGE plpgsql
AS $$
BEGIN
    PERFORM search_profile_add_policy_set_v1(actor_user_public_id => actor_user_public_id, search_profile_public_id_input => search_profile_public_id_input, policy_set_public_id_input => policy_set_public_id_input);
END;
$$;

CREATE OR REPLACE FUNCTION search_profile_remove_policy_set(
    actor_user_public_id UUID,
    search_profile_public_id_input UUID,
    policy_set_public_id_input UUID
)
RETURNS VOID
LANGUAGE plpgsql
AS $$
BEGIN
    PERFORM search_profile_remove_policy_set_v1(actor_user_public_id => actor_user_public_id, search_profile_public_id_input => search_profile_public_id_input, policy_set_public_id_input => policy_set_public_id_input);
END;
$$;

CREATE OR REPLACE FUNCTION search_profile_indexer_allow(
    actor_user_public_id UUID,
    search_profile_public_id_input UUID,
    indexer_instance_public_ids_input UUID[]
)
RETURNS VOID
LANGUAGE plpgsql
AS $$
BEGIN
    PERFORM search_profile_indexer_allow_v1(actor_user_public_id => actor_user_public_id, search_profile_public_id_input => search_profile_public_id_input, indexer_instance_public_ids_input => indexer_instance_public_ids_input);
END;
$$;

CREATE OR REPLACE FUNCTION search_profile_indexer_block(
    actor_user_public_id UUID,
    search_profile_public_id_input UUID,
    indexer_instance_public_ids_input UUID[]
)
RETURNS VOID
LANGUAGE plpgsql
AS $$
BEGIN
    PERFORM search_profile_indexer_block_v1(actor_user_public_id => actor_user_public_id, search_profile_public_id_input => search_profile_public_id_input, indexer_instance_public_ids_input => indexer_instance_public_ids_input);
END;
$$;

CREATE OR REPLACE FUNCTION search_profile_tag_allow(
    actor_user_public_id UUID,
    search_profile_public_id_input UUID,
    tag_public_ids_input UUID[],
    tag_keys_input TEXT[]
)
RETURNS VOID
LANGUAGE plpgsql
AS $$
BEGIN
    PERFORM search_profile_tag_allow_v1(actor_user_public_id => actor_user_public_id, search_profile_public_id_input => search_profile_public_id_input, tag_public_ids_input => tag_public_ids_input, tag_keys_input => tag_keys_input);
END;
$$;

CREATE OR REPLACE FUNCTION search_profile_tag_block(
    actor_user_public_id UUID,
    search_profile_public_id_input UUID,
    tag_public_ids_input UUID[],
    tag_keys_input TEXT[]
)
RETURNS VOID
LANGUAGE plpgsql
AS $$
BEGIN
    PERFORM search_profile_tag_block_v1(actor_user_public_id => actor_user_public_id, search_profile_public_id_input => search_profile_public_id_input, tag_public_ids_input => tag_public_ids_input, tag_keys_input => tag_keys_input);
END;
$$;

CREATE OR REPLACE FUNCTION search_profile_tag_prefer(
    actor_user_public_id UUID,
    search_profile_public_id_input UUID,
    tag_public_ids_input UUID[],
    tag_keys_input TEXT[]
)
RETURNS VOID
LANGUAGE plpgsql
AS $$
BEGIN
    PERFORM search_profile_tag_prefer_v1(actor_user_public_id => actor_user_public_id, search_profile_public_id_input => search_profile_public_id_input, tag_public_ids_input => tag_public_ids_input, tag_keys_input => tag_keys_input);
END;
$$;

CREATE OR REPLACE FUNCTION policy_rule_create(
    actor_user_public_id UUID,
    policy_set_public_id_input UUID,
    rule_type_input policy_rule_type,
    match_field_input policy_match_field,
    match_operator_input policy_match_operator,
    sort_order_input INTEGER,
    match_value_text_input VARCHAR,
    match_value_int_input INTEGER,
    match_value_uuid_input UUID,
    value_set_items_input policy_rule_value_item[],
    action_input policy_action,
    severity_input policy_severity,
    is_case_insensitive_input BOOLEAN,
    rationale_input VARCHAR,
    expires_at_input TIMESTAMPTZ
)
RETURNS UUID
LANGUAGE sql
AS $$
    SELECT policy_rule_create_v1(actor_user_public_id => actor_user_public_id, policy_set_public_id_input => policy_set_public_id_input, rule_type_input => rule_type_input, match_field_input => match_field_input, match_operator_input => match_operator_input, sort_order_input => sort_order_input, match_value_text_input => match_value_text_input, match_value_int_input => match_value_int_input, match_value_uuid_input => match_value_uuid_input, value_set_items_input => value_set_items_input, action_input => action_input, severity_input => severity_input, is_case_insensitive_input => is_case_insensitive_input, rationale_input => rationale_input, expires_at_input => expires_at_input);
$$;

CREATE OR REPLACE FUNCTION outbound_request_log_write(
    indexer_instance_public_id_input UUID,
    routing_policy_public_id_input UUID,
    search_request_public_id_input UUID,
    request_type_input outbound_request_type,
    correlation_id_input UUID,
    retry_seq_input SMALLINT,
    started_at_input TIMESTAMPTZ,
    finished_at_input TIMESTAMPTZ,
    outcome_input outbound_request_outcome,
    via_mitigation_input outbound_via_mitigation,
    rate_limit_denied_scope_input rate_limit_scope,
    error_class_input error_class,
    http_status_input INTEGER,
    latency_ms_input INTEGER,
    parse_ok_input BOOLEAN,
    result_count_input INTEGER,
    cf_detected_input BOOLEAN,
    page_number_input INTEGER,
    page_cursor_key_input VARCHAR
)
RETURNS VOID
LANGUAGE plpgsql
AS $$
BEGIN
    PERFORM outbound_request_log_write_v1(indexer_instance_public_id_input => indexer_instance_public_id_input, routing_policy_public_id_input => routing_policy_public_id_input, search_request_public_id_input => search_request_public_id_input, request_type_input => request_type_input, correlation_id_input => correlation_id_input, retry_seq_input => retry_seq_input, started_at_input => started_at_input, finished_at_input => finished_at_input, outcome_input => outcome_input, via_mitigation_input => via_mitigation_input, rate_limit_denied_scope_input => rate_limit_denied_scope_input, error_class_input => error_class_input, http_status_input => http_status_input, latency_ms_input => latency_ms_input, parse_ok_input => parse_ok_input, result_count_input => result_count_input, cf_detected_input => cf_detected_input, page_number_input => page_number_input, page_cursor_key_input => page_cursor_key_input);
END;
$$;

CREATE OR REPLACE FUNCTION torznab_instance_enable_disable(
    actor_user_public_id UUID,
    torznab_instance_public_id_input UUID,
    is_enabled_input BOOLEAN
)
RETURNS VOID
LANGUAGE plpgsql
AS $$
BEGIN
    PERFORM torznab_instance_enable_disable_v1(actor_user_public_id => actor_user_public_id, torznab_instance_public_id_input => torznab_instance_public_id_input, is_enabled_input => is_enabled_input);
END;
$$;

CREATE OR REPLACE FUNCTION torznab_instance_soft_delete(
    actor_user_public_id UUID,
    torznab_instance_public_id_input UUID
)
RETURNS VOID
LANGUAGE plpgsql
AS $$
BEGIN
    PERFORM torznab_instance_soft_delete_v1(actor_user_public_id => actor_user_public_id, torznab_instance_public_id_input => torznab_instance_public_id_input);
END;
$$;

CREATE OR REPLACE FUNCTION source_metadata_conflict_resolve(
    actor_user_public_id UUID,
    conflict_id_input BIGINT,
    resolution_input conflict_resolution,
    resolution_note_input VARCHAR
)
RETURNS VOID
LANGUAGE plpgsql
AS $$
BEGIN
    PERFORM source_metadata_conflict_resolve_v1(actor_user_public_id => actor_user_public_id, conflict_id_input => conflict_id_input, resolution_input => resolution_input, resolution_note_input => resolution_note_input);
END;
$$;

CREATE OR REPLACE FUNCTION source_metadata_conflict_reopen(
    actor_user_public_id UUID,
    conflict_id_input BIGINT,
    resolution_note_input VARCHAR
)
RETURNS VOID
LANGUAGE plpgsql
AS $$
BEGIN
    PERFORM source_metadata_conflict_reopen_v1(actor_user_public_id => actor_user_public_id, conflict_id_input => conflict_id_input, resolution_note_input => resolution_note_input);
END;
$$;

CREATE OR REPLACE FUNCTION job_claim_next(
    job_key_input job_key
)
RETURNS VOID
LANGUAGE plpgsql
AS $$
BEGIN
    PERFORM job_claim_next_v1(job_key_input => job_key_input);
END;
$$;

CREATE OR REPLACE FUNCTION job_run_retention_purge(
)
RETURNS VOID
LANGUAGE plpgsql
AS $$
BEGIN
    PERFORM job_run_retention_purge_v1();
END;
$$;

CREATE OR REPLACE FUNCTION search_request_cancel(
    actor_user_public_id UUID,
    search_request_public_id_input UUID
)
RETURNS VOID
LANGUAGE plpgsql
AS $$
BEGIN
    PERFORM search_request_cancel_v1(actor_user_public_id => actor_user_public_id, search_request_public_id_input => search_request_public_id_input);
END;
$$;

CREATE OR REPLACE FUNCTION search_indexer_run_enqueue(
    search_request_public_id_input UUID,
    indexer_instance_public_id_input UUID
)
RETURNS VOID
LANGUAGE plpgsql
AS $$
BEGIN
    PERFORM search_indexer_run_enqueue_v1(search_request_public_id_input => search_request_public_id_input, indexer_instance_public_id_input => indexer_instance_public_id_input);
END;
$$;

CREATE OR REPLACE FUNCTION search_indexer_run_mark_started(
    search_request_public_id_input UUID,
    indexer_instance_public_id_input UUID
)
RETURNS VOID
LANGUAGE plpgsql
AS $$
BEGIN
    PERFORM search_indexer_run_mark_started_v1(search_request_public_id_input => search_request_public_id_input, indexer_instance_public_id_input => indexer_instance_public_id_input);
END;
$$;

CREATE OR REPLACE FUNCTION search_indexer_run_mark_finished(
    search_request_public_id_input UUID,
    indexer_instance_public_id_input UUID,
    items_seen_delta_input INTEGER,
    items_emitted_delta_input INTEGER,
    canonical_added_delta_input INTEGER
)
RETURNS VOID
LANGUAGE plpgsql
AS $$
BEGIN
    PERFORM search_indexer_run_mark_finished_v1(search_request_public_id_input => search_request_public_id_input, indexer_instance_public_id_input => indexer_instance_public_id_input, items_seen_delta_input => items_seen_delta_input, items_emitted_delta_input => items_emitted_delta_input, canonical_added_delta_input => canonical_added_delta_input);
END;
$$;

CREATE OR REPLACE FUNCTION search_indexer_run_mark_failed(
    search_request_public_id_input UUID,
    indexer_instance_public_id_input UUID,
    error_class_input error_class,
    error_detail_input VARCHAR,
    retry_after_seconds_input INTEGER,
    retry_seq_input SMALLINT,
    rate_limit_scope_input rate_limit_scope
)
RETURNS VOID
LANGUAGE plpgsql
AS $$
BEGIN
    PERFORM search_indexer_run_mark_failed_v1(search_request_public_id_input => search_request_public_id_input, indexer_instance_public_id_input => indexer_instance_public_id_input, error_class_input => error_class_input, error_detail_input => error_detail_input, retry_after_seconds_input => retry_after_seconds_input, retry_seq_input => retry_seq_input, rate_limit_scope_input => rate_limit_scope_input);
END;
$$;

CREATE OR REPLACE FUNCTION search_indexer_run_mark_canceled(
    search_request_public_id_input UUID,
    indexer_instance_public_id_input UUID
)
RETURNS VOID
LANGUAGE plpgsql
AS $$
BEGIN
    PERFORM search_indexer_run_mark_canceled_v1(search_request_public_id_input => search_request_public_id_input, indexer_instance_public_id_input => indexer_instance_public_id_input);
END;
$$;

CREATE OR REPLACE FUNCTION canonical_disambiguation_rule_create(
    actor_user_public_id UUID,
    rule_type_input disambiguation_rule_type,
    identity_left_type_input disambiguation_identity_type,
    identity_left_value_text_input VARCHAR,
    identity_left_value_uuid_input UUID,
    identity_right_type_input disambiguation_identity_type,
    identity_right_value_text_input VARCHAR,
    identity_right_value_uuid_input UUID,
    reason_input VARCHAR
)
RETURNS VOID
LANGUAGE plpgsql
AS $$
BEGIN
    PERFORM canonical_disambiguation_rule_create_v1(actor_user_public_id => actor_user_public_id, rule_type_input => rule_type_input, identity_left_type_input => identity_left_type_input, identity_left_value_text_input => identity_left_value_text_input, identity_left_value_uuid_input => identity_left_value_uuid_input, identity_right_type_input => identity_right_type_input, identity_right_value_text_input => identity_right_value_text_input, identity_right_value_uuid_input => identity_right_value_uuid_input, reason_input => reason_input);
END;
$$;

CREATE OR REPLACE FUNCTION search_request_create(
    actor_user_public_id UUID,
    query_text_input VARCHAR,
    query_type_input query_type,
    torznab_mode_input torznab_mode,
    requested_media_domain_key_input VARCHAR,
    page_size_input INTEGER,
    search_profile_public_id_input UUID,
    request_policy_set_public_id_input UUID,
    season_number_input INTEGER,
    episode_number_input INTEGER,
    identifier_types_input identifier_type[],
    identifier_values_input TEXT[],
    torznab_cat_ids_input INTEGER[]
)
RETURNS TABLE(search_request_public_id UUID, request_policy_set_public_id UUID)
LANGUAGE sql
AS $$
    SELECT * FROM search_request_create_v1(actor_user_public_id => actor_user_public_id, query_text_input => query_text_input, query_type_input => query_type_input, torznab_mode_input => torznab_mode_input, requested_media_domain_key_input => requested_media_domain_key_input, page_size_input => page_size_input, search_profile_public_id_input => search_profile_public_id_input, request_policy_set_public_id_input => request_policy_set_public_id_input, season_number_input => season_number_input, episode_number_input => episode_number_input, identifier_types_input => identifier_types_input, identifier_values_input => identifier_values_input, torznab_cat_ids_input => torznab_cat_ids_input);
$$;

CREATE OR REPLACE FUNCTION job_run_policy_snapshot_gc(
)
RETURNS VOID
LANGUAGE plpgsql
AS $$
BEGIN
    PERFORM job_run_policy_snapshot_gc_v1();
END;
$$;

CREATE OR REPLACE FUNCTION job_run_policy_snapshot_refcount_repair(
)
RETURNS VOID
LANGUAGE plpgsql
AS $$
BEGIN
    PERFORM job_run_policy_snapshot_refcount_repair_v1();
END;
$$;

CREATE OR REPLACE FUNCTION job_run_rate_limit_state_purge(
)
RETURNS VOID
LANGUAGE plpgsql
AS $$
BEGIN
    PERFORM job_run_rate_limit_state_purge_v1();
END;
$$;

CREATE OR REPLACE FUNCTION normalize_title(
    title_raw TEXT
)
RETURNS TEXT
LANGUAGE sql
AS $$
    SELECT normalize_title_v1(title_raw => title_raw);
$$;

CREATE OR REPLACE FUNCTION normalize_magnet_uri(
    raw_uri TEXT
)
RETURNS TEXT
LANGUAGE sql
AS $$
    SELECT normalize_magnet_uri_v1(raw_uri => raw_uri);
$$;

CREATE OR REPLACE FUNCTION derive_magnet_hash(
    infohash_v2_input TEXT,
    infohash_v1_input TEXT,
    magnet_uri_input TEXT
)
RETURNS TEXT
LANGUAGE sql
AS $$
    SELECT derive_magnet_hash_v1(infohash_v2_input => infohash_v2_input, infohash_v1_input => infohash_v1_input, magnet_uri_input => magnet_uri_input);
$$;

CREATE OR REPLACE FUNCTION compute_title_size_hash(
    title_normalized_input TEXT,
    size_bytes_input BIGINT
)
RETURNS TEXT
LANGUAGE sql
AS $$
    SELECT compute_title_size_hash_v1(title_normalized_input => title_normalized_input, size_bytes_input => size_bytes_input);
$$;

CREATE OR REPLACE FUNCTION policy_text_match(
    candidate_input TEXT,
    match_operator_input policy_match_operator,
    match_value_text_input TEXT,
    value_set_id_input BIGINT,
    is_case_insensitive_input BOOLEAN
)
RETURNS BOOLEAN
LANGUAGE sql
AS $$
    SELECT policy_text_match_v1(candidate_input => candidate_input, match_operator_input => match_operator_input, match_value_text_input => match_value_text_input, value_set_id_input => value_set_id_input, is_case_insensitive_input => is_case_insensitive_input);
$$;

CREATE OR REPLACE FUNCTION policy_uuid_match(
    candidate_input UUID,
    match_operator_input policy_match_operator,
    match_value_uuid_input UUID,
    value_set_id_input BIGINT
)
RETURNS BOOLEAN
LANGUAGE sql
AS $$
    SELECT policy_uuid_match_v1(candidate_input => candidate_input, match_operator_input => match_operator_input, match_value_uuid_input => match_value_uuid_input, value_set_id_input => value_set_id_input);
$$;

CREATE OR REPLACE FUNCTION policy_int_match(
    candidate_input INTEGER,
    match_operator_input policy_match_operator,
    match_value_int_input INTEGER,
    value_set_id_input BIGINT
)
RETURNS BOOLEAN
LANGUAGE sql
AS $$
    SELECT policy_int_match_v1(candidate_input => candidate_input, match_operator_input => match_operator_input, match_value_int_input => match_value_int_input, value_set_id_input => value_set_id_input);
$$;

CREATE OR REPLACE FUNCTION policy_release_group_match(
    canonical_torrent_id_input BIGINT,
    release_group_token_input TEXT,
    match_operator_input policy_match_operator,
    match_value_text_input TEXT,
    value_set_id_input BIGINT,
    is_case_insensitive_input BOOLEAN
)
RETURNS BOOLEAN
LANGUAGE sql
AS $$
    SELECT policy_release_group_match_v1(canonical_torrent_id_input => canonical_torrent_id_input, release_group_token_input => release_group_token_input, match_operator_input => match_operator_input, match_value_text_input => match_value_text_input, value_set_id_input => value_set_id_input, is_case_insensitive_input => is_case_insensitive_input);
$$;

CREATE OR REPLACE FUNCTION log_source_metadata_conflict(
    canonical_torrent_source_id_input BIGINT,
    indexer_instance_id_input BIGINT,
    conflict_type_input conflict_type,
    existing_value_input TEXT,
    incoming_value_input TEXT,
    observed_at_input TIMESTAMPTZ
)
RETURNS VOID
LANGUAGE plpgsql
AS $$
BEGIN
    PERFORM log_source_metadata_conflict_v1(canonical_torrent_source_id_input => canonical_torrent_source_id_input, indexer_instance_id_input => indexer_instance_id_input, conflict_type_input => conflict_type_input, existing_value_input => existing_value_input, incoming_value_input => incoming_value_input, observed_at_input => observed_at_input);
END;
$$;

CREATE OR REPLACE FUNCTION search_result_ingest(
    search_request_public_id_input UUID,
    indexer_instance_public_id_input UUID,
    source_guid_input VARCHAR,
    details_url_input VARCHAR,
    download_url_input VARCHAR,
    magnet_uri_input VARCHAR,
    title_raw_input VARCHAR,
    size_bytes_input BIGINT,
    infohash_v1_input CHAR(40),
    infohash_v2_input CHAR(64),
    magnet_hash_input CHAR(64),
    seeders_input INTEGER,
    leechers_input INTEGER,
    published_at_input TIMESTAMPTZ,
    uploader_input VARCHAR,
    observed_at_input TIMESTAMPTZ,
    attr_keys_input observation_attr_key[],
    attr_types_input attr_value_type[],
    attr_value_text_input VARCHAR[],
    attr_value_int_input INTEGER[],
    attr_value_bigint_input BIGINT[],
    attr_value_numeric_input NUMERIC(12, 4)[],
    attr_value_bool_input BOOLEAN[],
    attr_value_uuid_input UUID[]
)
RETURNS TABLE(
    canonical_torrent_public_id UUID,
    canonical_torrent_source_public_id UUID,
    observation_created BOOLEAN,
    durable_source_created BOOLEAN,
    canonical_changed BOOLEAN
)
LANGUAGE sql
AS $$
    SELECT * FROM search_result_ingest_v1(search_request_public_id_input => search_request_public_id_input, indexer_instance_public_id_input => indexer_instance_public_id_input, source_guid_input => source_guid_input, details_url_input => details_url_input, download_url_input => download_url_input, magnet_uri_input => magnet_uri_input, title_raw_input => title_raw_input, size_bytes_input => size_bytes_input, infohash_v1_input => infohash_v1_input, infohash_v2_input => infohash_v2_input, magnet_hash_input => magnet_hash_input, seeders_input => seeders_input, leechers_input => leechers_input, published_at_input => published_at_input, uploader_input => uploader_input, observed_at_input => observed_at_input, attr_keys_input => attr_keys_input, attr_types_input => attr_types_input, attr_value_text_input => attr_value_text_input, attr_value_int_input => attr_value_int_input, attr_value_bigint_input => attr_value_bigint_input, attr_value_numeric_input => attr_value_numeric_input, attr_value_bool_input => attr_value_bool_input, attr_value_uuid_input => attr_value_uuid_input);
$$;

CREATE OR REPLACE FUNCTION canonical_recompute_best_source(
    canonical_torrent_public_id_input UUID,
    scoring_context_input scoring_context DEFAULT 'global_current'
)
RETURNS UUID
LANGUAGE sql
AS $$
    SELECT canonical_recompute_best_source_v1(canonical_torrent_public_id_input => canonical_torrent_public_id_input, scoring_context_input => scoring_context_input);
$$;

CREATE OR REPLACE FUNCTION canonical_prune_low_confidence(
)
RETURNS VOID
LANGUAGE plpgsql
AS $$
BEGIN
    PERFORM canonical_prune_low_confidence_v1();
END;
$$;

CREATE OR REPLACE FUNCTION canonical_merge_by_infohash(
    infohash_v2_input CHAR(64),
    infohash_v1_input CHAR(40)
)
RETURNS VOID
LANGUAGE plpgsql
AS $$
BEGIN
    PERFORM canonical_merge_by_infohash_v1(infohash_v2_input => infohash_v2_input, infohash_v1_input => infohash_v1_input);
END;
$$;

CREATE OR REPLACE FUNCTION job_run_connectivity_profile_refresh(
)
RETURNS VOID
LANGUAGE plpgsql
AS $$
BEGIN
    PERFORM job_run_connectivity_profile_refresh_v1();
END;
$$;

CREATE OR REPLACE FUNCTION job_run_reputation_rollup(
    window_key_input reputation_window
)
RETURNS VOID
LANGUAGE plpgsql
AS $$
BEGIN
    PERFORM job_run_reputation_rollup_v1(window_key_input => window_key_input);
END;
$$;

CREATE OR REPLACE FUNCTION job_run_canonical_backfill_best_source(
)
RETURNS VOID
LANGUAGE plpgsql
AS $$
BEGIN
    PERFORM job_run_canonical_backfill_best_source_v1();
END;
$$;

CREATE OR REPLACE FUNCTION job_run_rss_subscription_backfill(
)
RETURNS VOID
LANGUAGE plpgsql
AS $$
BEGIN
    PERFORM job_run_rss_subscription_backfill_v1();
END;
$$;

CREATE OR REPLACE FUNCTION job_run_base_score_refresh_recent(
)
RETURNS VOID
LANGUAGE plpgsql
AS $$
BEGIN
    PERFORM job_run_base_score_refresh_recent_v1();
END;
$$;

CREATE OR REPLACE FUNCTION secret_create(
    actor_user_public_id UUID,
    secret_type_input secret_type,
    plaintext_value_input VARCHAR
)
RETURNS UUID
LANGUAGE sql
AS $$
    SELECT secret_create_v1(actor_user_public_id => actor_user_public_id, secret_type_input => secret_type_input, plaintext_value_input => plaintext_value_input);
$$;

CREATE OR REPLACE FUNCTION secret_rotate(
    actor_user_public_id UUID,
    secret_public_id_input UUID,
    plaintext_value_input VARCHAR
)
RETURNS UUID
LANGUAGE sql
AS $$
    SELECT secret_rotate_v1(actor_user_public_id => actor_user_public_id, secret_public_id_input => secret_public_id_input, plaintext_value_input => plaintext_value_input);
$$;

CREATE OR REPLACE FUNCTION secret_revoke(
    actor_user_public_id UUID,
    secret_public_id_input UUID
)
RETURNS VOID
LANGUAGE plpgsql
AS $$
BEGIN
    PERFORM secret_revoke_v1(actor_user_public_id => actor_user_public_id, secret_public_id_input => secret_public_id_input);
END;
$$;

CREATE OR REPLACE FUNCTION torznab_instance_create(
    actor_user_public_id UUID,
    search_profile_public_id_input UUID,
    display_name_input VARCHAR
)
RETURNS TABLE(
    torznab_instance_public_id UUID,
    api_key_plaintext VARCHAR
)
LANGUAGE sql
AS $$
    SELECT * FROM torznab_instance_create_v1(actor_user_public_id => actor_user_public_id, search_profile_public_id_input => search_profile_public_id_input, display_name_input => display_name_input);
$$;

CREATE OR REPLACE FUNCTION torznab_instance_rotate_key(
    actor_user_public_id UUID,
    torznab_instance_public_id_input UUID
)
RETURNS VARCHAR
LANGUAGE sql
AS $$
    SELECT torznab_instance_rotate_key_v1(actor_user_public_id => actor_user_public_id, torznab_instance_public_id_input => torznab_instance_public_id_input);
$$;

CREATE OR REPLACE FUNCTION import_job_create(
    actor_user_public_id UUID,
    source_input import_source,
    is_dry_run_input BOOLEAN,
    target_search_profile_public_id_input UUID,
    target_torznab_instance_public_id_input UUID
)
RETURNS UUID
LANGUAGE sql
AS $$
    SELECT import_job_create_v1(actor_user_public_id => actor_user_public_id, source_input => source_input, is_dry_run_input => is_dry_run_input, target_search_profile_public_id_input => target_search_profile_public_id_input, target_torznab_instance_public_id_input => target_torznab_instance_public_id_input);
$$;

CREATE OR REPLACE FUNCTION import_job_run_prowlarr_api(
    import_job_public_id_input UUID,
    prowlarr_url_input VARCHAR,
    prowlarr_api_key_secret_public_id_input UUID
)
RETURNS VOID
LANGUAGE plpgsql
AS $$
BEGIN
    PERFORM import_job_run_prowlarr_api_v1(import_job_public_id_input => import_job_public_id_input, prowlarr_url_input => prowlarr_url_input, prowlarr_api_key_secret_public_id_input => prowlarr_api_key_secret_public_id_input);
END;
$$;

CREATE OR REPLACE FUNCTION import_job_run_prowlarr_backup(
    import_job_public_id_input UUID,
    backup_blob_ref_input VARCHAR
)
RETURNS VOID
LANGUAGE plpgsql
AS $$
BEGIN
    PERFORM import_job_run_prowlarr_backup_v1(import_job_public_id_input => import_job_public_id_input, backup_blob_ref_input => backup_blob_ref_input);
END;
$$;

CREATE OR REPLACE FUNCTION import_job_get_status(
    import_job_public_id_input UUID
)
RETURNS TABLE(
    status import_job_status,
    result_total INTEGER,
    result_imported_ready INTEGER,
    result_imported_needs_secret INTEGER,
    result_imported_test_failed INTEGER,
    result_unmapped_definition INTEGER,
    result_skipped_duplicate INTEGER
)
LANGUAGE sql
AS $$
    SELECT * FROM import_job_get_status_v1(import_job_public_id_input => import_job_public_id_input);
$$;

CREATE OR REPLACE FUNCTION import_job_list_results(
    import_job_public_id_input UUID
)
RETURNS TABLE(
    prowlarr_identifier VARCHAR,
    upstream_slug VARCHAR,
    indexer_instance_public_id UUID,
    status import_indexer_result_status,
    detail VARCHAR,
    created_at TIMESTAMPTZ
)
LANGUAGE sql
AS $$
    SELECT * FROM import_job_list_results_v1(import_job_public_id_input => import_job_public_id_input);
$$;

CREATE OR REPLACE FUNCTION secret_read(
    actor_user_public_id UUID,
    secret_public_id_input UUID
)
RETURNS TABLE (
    secret_type secret_type,
    cipher_text BYTEA,
    key_id VARCHAR
)
LANGUAGE sql
AS $$
    SELECT * FROM secret_read_v1(actor_user_public_id => actor_user_public_id, secret_public_id_input => secret_public_id_input);
$$;

CREATE OR REPLACE FUNCTION rss_poll_claim(
    limit_input INTEGER DEFAULT 25
)
RETURNS TABLE (
    rss_subscription_id BIGINT,
    indexer_instance_public_id UUID,
    routing_policy_public_id UUID,
    interval_seconds INTEGER,
    connect_timeout_ms INTEGER,
    read_timeout_ms INTEGER,
    correlation_id UUID,
    retry_seq SMALLINT
)
LANGUAGE sql
AS $$
    SELECT * FROM rss_poll_claim_v1(limit_input => limit_input);
$$;

CREATE OR REPLACE FUNCTION rss_poll_apply(
    rss_subscription_id_input BIGINT,
    correlation_id_input UUID,
    retry_seq_input SMALLINT,
    started_at_input TIMESTAMPTZ,
    finished_at_input TIMESTAMPTZ,
    outcome_input outbound_request_outcome,
    error_class_input error_class,
    http_status_input INTEGER,
    latency_ms_input INTEGER,
    parse_ok_input BOOLEAN,
    result_count_input INTEGER,
    via_mitigation_input outbound_via_mitigation,
    rate_limit_denied_scope_input rate_limit_scope,
    cf_detected_input BOOLEAN,
    cf_retryable_input BOOLEAN,
    item_guid_input VARCHAR[],
    infohash_v1_input CHAR(40)[],
    infohash_v2_input CHAR(64)[],
    magnet_hash_input CHAR(64)[]
)
RETURNS TABLE (
    items_parsed INTEGER,
    items_eligible INTEGER,
    items_inserted INTEGER,
    subscription_succeeded BOOLEAN
)
LANGUAGE sql
AS $$
    SELECT * FROM rss_poll_apply_v1(rss_subscription_id_input => rss_subscription_id_input, correlation_id_input => correlation_id_input, retry_seq_input => retry_seq_input, started_at_input => started_at_input, finished_at_input => finished_at_input, outcome_input => outcome_input, error_class_input => error_class_input, http_status_input => http_status_input, latency_ms_input => latency_ms_input, parse_ok_input => parse_ok_input, result_count_input => result_count_input, via_mitigation_input => via_mitigation_input, rate_limit_denied_scope_input => rate_limit_denied_scope_input, cf_detected_input => cf_detected_input, cf_retryable_input => cf_retryable_input, item_guid_input => item_guid_input, infohash_v1_input => infohash_v1_input, infohash_v2_input => infohash_v2_input, magnet_hash_input => magnet_hash_input);
$$;

CREATE OR REPLACE FUNCTION indexer_instance_test_prepare(
    actor_user_public_id UUID,
    indexer_instance_public_id_input UUID
)
RETURNS TABLE (
    can_execute BOOLEAN,
    error_class error_class,
    error_code VARCHAR(64),
    detail VARCHAR(256),
    engine engine,
    routing_policy_public_id UUID,
    connect_timeout_ms INTEGER,
    read_timeout_ms INTEGER,
    field_names VARCHAR[],
    field_types field_type[],
    value_plain VARCHAR[],
    value_int INTEGER[],
    value_decimal NUMERIC[],
    value_bool BOOLEAN[],
    secret_public_ids UUID[]
)
LANGUAGE sql
AS $$
    SELECT * FROM indexer_instance_test_prepare_v1(actor_user_public_id => actor_user_public_id, indexer_instance_public_id_input => indexer_instance_public_id_input);
$$;

CREATE OR REPLACE FUNCTION indexer_instance_test_finalize(
    actor_user_public_id UUID,
    indexer_instance_public_id_input UUID,
    ok_input BOOLEAN,
    error_class_input error_class,
    error_code_input VARCHAR(64),
    detail_input VARCHAR(256),
    result_count_input INTEGER
)
RETURNS TABLE (
    ok BOOLEAN,
    error_class error_class,
    error_code VARCHAR(64),
    detail VARCHAR(256),
    result_count INTEGER
)
LANGUAGE sql
AS $$
    SELECT * FROM indexer_instance_test_finalize_v1(actor_user_public_id => actor_user_public_id, indexer_instance_public_id_input => indexer_instance_public_id_input, ok_input => ok_input, error_class_input => error_class_input, error_code_input => error_code_input, detail_input => detail_input, result_count_input => result_count_input);
$$;

