[package]
name = "revaer-data"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
version.workspace = true
authors.workspace = true
repository.workspace = true
publish = false
description = "Shared data access layer for Revaer schema initialization and stored procedures."

[dependencies]
chrono.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
sqlx.workspace = true
uuid.workspace = true
revaer-torrent-core = { path = "../revaer-torrent-core" }
revaer-events = { path = "../revaer-events" }
tracing.workspace = true
tokio.workspace = true

[dev-dependencies]
anyhow.workspace = true
revaer-test-support = { path = "../revaer-test-support" }
