//! # Design
//!
//! - Centralize compile-time `OpenAPI` asset paths to keep `openapi.rs` path-free.
//! - Keep constants small and crate-private to avoid leaking filesystem layout.
//! - Treat missing/invalid assets as build-time failures via `include_str!`.

/// Embedded `OpenAPI` JSON generated by `just api-export`.
pub(crate) const OPENAPI_EMBEDDED_JSON: &str = include_str!(concat!(
    env!("CARGO_MANIFEST_DIR"),
    "/../../docs/api/openapi.json"
));

/// File name used when persisting the `OpenAPI` document.
pub(crate) const OPENAPI_FILENAME: &str = "openapi.json";

/// Build the default `OpenAPI` output path relative to the workspace root.
pub(crate) fn openapi_output_path() -> std::path::PathBuf {
    std::path::PathBuf::from_iter(["docs", "api", OPENAPI_FILENAME])
}
