/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/.well-known/revaer.json": {
    /** Retrieve the configuration snapshot exposed to clients */
    get: {
      responses: {
        /** @description Configuration document */
        200: {
          content: {
            "application/json": components["schemas"]["ConfigSnapshot"];
          };
        };
      };
    };
  };
  "/admin/factory-reset": {
    /** Reset configuration to defaults */
    post: {
      requestBody: {
        content: {
          "application/json": components["schemas"]["FactoryResetRequest"];
        };
      };
      responses: {
        /** @description Factory reset complete */
        204: {
          content: never;
        };
        /** @description Invalid confirmation */
        400: {
          content: {
            "application/json": components["schemas"]["ProblemDetails"];
          };
        };
        /** @description Authentication failed */
        401: {
          content: {
            "application/json": components["schemas"]["ProblemDetails"];
          };
        };
        /** @description Rate limit exceeded */
        429: {
          content: {
            "application/json": components["schemas"]["ProblemDetails"];
          };
        };
      };
    };
  };
  "/admin/settings": {
    /** Apply configuration mutations */
    patch: {
      requestBody: {
        content: {
          "application/json": components["schemas"]["SettingsChangeset"];
        };
      };
      responses: {
        /** @description Updated configuration snapshot */
        200: {
          content: {
            "application/json": components["schemas"]["ConfigSnapshot"];
          };
        };
        /** @description Authentication failed */
        401: {
          content: {
            "application/json": components["schemas"]["ProblemDetails"];
          };
        };
        /** @description Validation error */
        422: {
          content: {
            "application/json": components["schemas"]["ProblemDetails"];
          };
        };
        /** @description Rate limit exceeded */
        429: {
          content: {
            "application/json": components["schemas"]["ProblemDetails"];
          };
        };
      };
    };
  };
  "/admin/setup/complete": {
    /** Complete initial setup and persist configuration */
    post: {
      requestBody: {
        content: {
          "application/json": components["schemas"]["SettingsChangeset"];
        };
      };
      responses: {
        /** @description Snapshot after setup */
        200: {
          content: {
            "application/json": components["schemas"]["SetupCompleteResponse"];
          };
        };
        /** @description Invalid setup token */
        401: {
          content: {
            "application/json": components["schemas"]["ProblemDetails"];
          };
        };
      };
    };
  };
  "/admin/setup/start": {
    /** Issue a one-time setup token */
    post: {
      requestBody?: {
        content: {
          "application/json": components["schemas"]["SetupStartRequest"];
        };
      };
      responses: {
        /** @description Setup token issued */
        200: {
          content: {
            "application/json": components["schemas"]["SetupStartResponse"];
          };
        };
        /** @description System already configured */
        409: {
          content: {
            "application/json": components["schemas"]["ProblemDetails"];
          };
        };
      };
    };
  };
  "/admin/torrents": {
    /** List torrents (admin) */
    get: {
      parameters: {
        query?: {
          limit?: number;
          cursor?: string;
          state?: "queued" | "fetching_metadata" | "downloading" | "seeding" | "completed" | "failed" | "stopped";
          tracker?: string;
          extension?: string;
          /** @description Comma separated list of tags */
          tags?: string;
          name?: string;
        };
      };
      responses: {
        /** @description Torrent collection */
        200: {
          content: {
            "application/json": components["schemas"]["TorrentListResponse"];
          };
        };
        /** @description Invalid filters */
        400: {
          content: {
            "application/json": components["schemas"]["ProblemDetails"];
          };
        };
        /** @description Authentication failed */
        401: {
          content: {
            "application/json": components["schemas"]["ProblemDetails"];
          };
        };
        /** @description Rate limit exceeded */
        429: {
          content: {
            "application/json": components["schemas"]["ProblemDetails"];
          };
        };
        /** @description Torrent workflow unavailable */
        503: {
          content: {
            "application/json": components["schemas"]["ProblemDetails"];
          };
        };
      };
    };
    /** Submit a torrent descriptor (admin) */
    post: {
      requestBody: {
        content: {
          "application/json": components["schemas"]["TorrentCreateRequest"];
        };
      };
      responses: {
        /** @description Torrent accepted */
        202: {
          content: never;
        };
        /** @description Invalid submission */
        400: {
          content: {
            "application/json": components["schemas"]["ProblemDetails"];
          };
        };
        /** @description Authentication failed */
        401: {
          content: {
            "application/json": components["schemas"]["ProblemDetails"];
          };
        };
        /** @description Rate limit exceeded */
        429: {
          content: {
            "application/json": components["schemas"]["ProblemDetails"];
          };
        };
        /** @description Torrent workflow unavailable */
        503: {
          content: {
            "application/json": components["schemas"]["ProblemDetails"];
          };
        };
      };
    };
  };
  "/admin/torrents/categories": {
    /** List torrent categories (admin) */
    get: {
      responses: {
        /** @description Category list */
        200: {
          content: {
            "application/json": components["schemas"]["TorrentLabelEntry"][];
          };
        };
        /** @description Authentication failed */
        401: {
          content: {
            "application/json": components["schemas"]["ProblemDetails"];
          };
        };
        /** @description Rate limit exceeded */
        429: {
          content: {
            "application/json": components["schemas"]["ProblemDetails"];
          };
        };
        /** @description Torrent workflow unavailable */
        503: {
          content: {
            "application/json": components["schemas"]["ProblemDetails"];
          };
        };
      };
    };
  };
  "/admin/torrents/categories/{name}": {
    /** Upsert torrent category (admin) */
    put: {
      parameters: {
        path: {
          name: string;
        };
      };
      requestBody: {
        content: {
          "application/json": components["schemas"]["TorrentLabelPolicy"];
        };
      };
      responses: {
        /** @description Category updated */
        200: {
          content: {
            "application/json": components["schemas"]["TorrentLabelEntry"];
          };
        };
        /** @description Invalid category payload */
        400: {
          content: {
            "application/json": components["schemas"]["ProblemDetails"];
          };
        };
        /** @description Authentication failed */
        401: {
          content: {
            "application/json": components["schemas"]["ProblemDetails"];
          };
        };
        /** @description Rate limit exceeded */
        429: {
          content: {
            "application/json": components["schemas"]["ProblemDetails"];
          };
        };
        /** @description Torrent workflow unavailable */
        503: {
          content: {
            "application/json": components["schemas"]["ProblemDetails"];
          };
        };
      };
    };
  };
  "/admin/torrents/create": {
    /** Author a torrent from filesystem (admin) */
    post: {
      requestBody: {
        content: {
          "application/json": components["schemas"]["TorrentAuthorRequest"];
        };
      };
      responses: {
        /** @description Torrent authored */
        200: {
          content: {
            "application/json": components["schemas"]["TorrentAuthorResponse"];
          };
        };
        /** @description Invalid authoring request */
        400: {
          content: {
            "application/json": components["schemas"]["ProblemDetails"];
          };
        };
        /** @description Authentication failed */
        401: {
          content: {
            "application/json": components["schemas"]["ProblemDetails"];
          };
        };
        /** @description Rate limit exceeded */
        429: {
          content: {
            "application/json": components["schemas"]["ProblemDetails"];
          };
        };
        /** @description Torrent workflow unavailable */
        503: {
          content: {
            "application/json": components["schemas"]["ProblemDetails"];
          };
        };
      };
    };
  };
  "/admin/torrents/tags": {
    /** List torrent tags (admin) */
    get: {
      responses: {
        /** @description Tag list */
        200: {
          content: {
            "application/json": components["schemas"]["TorrentLabelEntry"][];
          };
        };
        /** @description Authentication failed */
        401: {
          content: {
            "application/json": components["schemas"]["ProblemDetails"];
          };
        };
        /** @description Rate limit exceeded */
        429: {
          content: {
            "application/json": components["schemas"]["ProblemDetails"];
          };
        };
        /** @description Torrent workflow unavailable */
        503: {
          content: {
            "application/json": components["schemas"]["ProblemDetails"];
          };
        };
      };
    };
  };
  "/admin/torrents/tags/{name}": {
    /** Upsert torrent tag (admin) */
    put: {
      parameters: {
        path: {
          name: string;
        };
      };
      requestBody: {
        content: {
          "application/json": components["schemas"]["TorrentLabelPolicy"];
        };
      };
      responses: {
        /** @description Tag updated */
        200: {
          content: {
            "application/json": components["schemas"]["TorrentLabelEntry"];
          };
        };
        /** @description Invalid tag payload */
        400: {
          content: {
            "application/json": components["schemas"]["ProblemDetails"];
          };
        };
        /** @description Authentication failed */
        401: {
          content: {
            "application/json": components["schemas"]["ProblemDetails"];
          };
        };
        /** @description Rate limit exceeded */
        429: {
          content: {
            "application/json": components["schemas"]["ProblemDetails"];
          };
        };
        /** @description Torrent workflow unavailable */
        503: {
          content: {
            "application/json": components["schemas"]["ProblemDetails"];
          };
        };
      };
    };
  };
  "/admin/torrents/{id}": {
    /** Fetch torrent detail (admin) */
    get: {
      parameters: {
        path: {
          id: string;
        };
      };
      responses: {
        /** @description Torrent detail */
        200: {
          content: {
            "application/json": components["schemas"]["TorrentDetail"];
          };
        };
        /** @description Authentication failed */
        401: {
          content: {
            "application/json": components["schemas"]["ProblemDetails"];
          };
        };
        /** @description Torrent not found */
        404: {
          content: {
            "application/json": components["schemas"]["ProblemDetails"];
          };
        };
        /** @description Rate limit exceeded */
        429: {
          content: {
            "application/json": components["schemas"]["ProblemDetails"];
          };
        };
        /** @description Torrent workflow unavailable */
        503: {
          content: {
            "application/json": components["schemas"]["ProblemDetails"];
          };
        };
      };
    };
    /** Remove torrent (admin) */
    delete: {
      parameters: {
        path: {
          id: string;
        };
      };
      responses: {
        /** @description Torrent removed */
        204: {
          content: never;
        };
        /** @description Authentication failed */
        401: {
          content: {
            "application/json": components["schemas"]["ProblemDetails"];
          };
        };
        /** @description Rate limit exceeded */
        429: {
          content: {
            "application/json": components["schemas"]["ProblemDetails"];
          };
        };
        /** @description Torrent workflow unavailable */
        503: {
          content: {
            "application/json": components["schemas"]["ProblemDetails"];
          };
        };
      };
    };
  };
  "/admin/torrents/{id}/peers": {
    /** List torrent peers (admin) */
    get: {
      parameters: {
        path: {
          id: string;
        };
      };
      responses: {
        /** @description Peer list */
        200: {
          content: {
            "application/json": components["schemas"]["TorrentPeer"][];
          };
        };
        /** @description Authentication failed */
        401: {
          content: {
            "application/json": components["schemas"]["ProblemDetails"];
          };
        };
        /** @description Rate limit exceeded */
        429: {
          content: {
            "application/json": components["schemas"]["ProblemDetails"];
          };
        };
        /** @description Torrent workflow unavailable */
        503: {
          content: {
            "application/json": components["schemas"]["ProblemDetails"];
          };
        };
      };
    };
  };
  "/docs/openapi.json": {
    /** Serve the generated OpenAPI specification */
    get: {
      responses: {
        /** @description OpenAPI document */
        200: {
          content: {
            "application/json": Record<string, never>;
          };
        };
      };
    };
  };
  "/health": {
    /** Read the lightweight health probe */
    get: {
      responses: {
        /** @description Health snapshot */
        200: {
          content: {
            "application/json": components["schemas"]["HealthResponse"];
          };
        };
        /** @description Service unavailable */
        503: {
          content: {
            "application/json": components["schemas"]["ProblemDetails"];
          };
        };
      };
    };
  };
  "/health/full": {
    /** Read the extended health probe */
    get: {
      responses: {
        /** @description Detailed health snapshot */
        200: {
          content: {
            "application/json": components["schemas"]["FullHealthResponse"];
          };
        };
        /** @description Service unavailable */
        503: {
          content: {
            "application/json": components["schemas"]["ProblemDetails"];
          };
        };
      };
    };
  };
  "/metrics": {
    /** Expose Prometheus metrics */
    get: {
      responses: {
        /** @description Prometheus metrics */
        200: {
          content: {
            "text/plain": string;
          };
        };
      };
    };
  };
  "/v1/auth/refresh": {
    /** Refresh the active API key expiration */
    post: {
      responses: {
        /** @description Updated API key expiry */
        200: {
          content: {
            "application/json": components["schemas"]["ApiKeyRefreshResponse"];
          };
        };
        /** @description Authentication failed */
        401: {
          content: {
            "application/json": components["schemas"]["ProblemDetails"];
          };
        };
        /** @description Configuration invalid */
        422: {
          content: {
            "application/json": components["schemas"]["ProblemDetails"];
          };
        };
        /** @description Rate limit exceeded */
        429: {
          content: {
            "application/json": components["schemas"]["ProblemDetails"];
          };
        };
      };
    };
  };
  "/v1/config": {
    /** Retrieve the authenticated configuration snapshot */
    get: {
      responses: {
        /** @description Configuration snapshot */
        200: {
          content: {
            "application/json": components["schemas"]["ConfigSnapshot"];
          };
        };
        /** @description Authentication failed */
        401: {
          content: {
            "application/json": components["schemas"]["ProblemDetails"];
          };
        };
        /** @description Rate limit exceeded */
        429: {
          content: {
            "application/json": components["schemas"]["ProblemDetails"];
          };
        };
      };
    };
    /** Apply configuration mutations */
    patch: {
      requestBody: {
        content: {
          "application/json": components["schemas"]["SettingsChangeset"];
        };
      };
      responses: {
        /** @description Updated configuration snapshot */
        200: {
          content: {
            "application/json": components["schemas"]["ConfigSnapshot"];
          };
        };
        /** @description Authentication failed */
        401: {
          content: {
            "application/json": components["schemas"]["ProblemDetails"];
          };
        };
        /** @description Validation error */
        422: {
          content: {
            "application/json": components["schemas"]["ProblemDetails"];
          };
        };
        /** @description Rate limit exceeded */
        429: {
          content: {
            "application/json": components["schemas"]["ProblemDetails"];
          };
        };
      };
    };
  };
  "/v1/dashboard": {
    /** Retrieve dashboard snapshot */
    get: {
      responses: {
        /** @description Dashboard snapshot */
        200: {
          content: {
            "application/json": components["schemas"]["DashboardResponse"];
          };
        };
        /** @description Authentication failed */
        401: {
          content: {
            "application/json": components["schemas"]["ProblemDetails"];
          };
        };
        /** @description Rate limit exceeded */
        429: {
          content: {
            "application/json": components["schemas"]["ProblemDetails"];
          };
        };
      };
    };
  };
  "/v1/events": {
    /** Subscribe to events via SSE */
    get: {
      parameters: {
        query?: {
          /** @description Comma separated torrent identifiers */
          torrent?: string;
          /** @description Comma separated event kinds */
          event?: string;
          /** @description Filter state change events by new state */
          state?: string;
        };
      };
      responses: {
        /** @description SSE stream */
        200: {
          content: {
            "text/event-stream": string;
          };
        };
        /** @description Authentication failed */
        401: {
          content: {
            "application/json": components["schemas"]["ProblemDetails"];
          };
        };
        /** @description Rate limit exceeded */
        429: {
          content: {
            "application/json": components["schemas"]["ProblemDetails"];
          };
        };
        /** @description Event stream unavailable */
        503: {
          content: {
            "application/json": components["schemas"]["ProblemDetails"];
          };
        };
      };
    };
  };
  "/v1/events/stream": {
    /** Subscribe to events via SSE */
    get: {
      parameters: {
        query?: {
          /** @description Comma separated torrent identifiers */
          torrent?: string;
          /** @description Comma separated event kinds */
          event?: string;
          /** @description Filter state change events by new state */
          state?: string;
        };
      };
      responses: {
        /** @description SSE stream */
        200: {
          content: {
            "text/event-stream": string;
          };
        };
        /** @description Authentication failed */
        401: {
          content: {
            "application/json": components["schemas"]["ProblemDetails"];
          };
        };
        /** @description Rate limit exceeded */
        429: {
          content: {
            "application/json": components["schemas"]["ProblemDetails"];
          };
        };
        /** @description Event stream unavailable */
        503: {
          content: {
            "application/json": components["schemas"]["ProblemDetails"];
          };
        };
      };
    };
  };
  "/v1/fs/browse": {
    /** Browse filesystem entries */
    get: {
      parameters: {
        query?: {
          path?: string;
        };
      };
      responses: {
        /** @description Filesystem entries */
        200: {
          content: {
            "application/json": components["schemas"]["FsBrowseResponse"];
          };
        };
        /** @description Invalid filesystem path */
        400: {
          content: {
            "application/json": components["schemas"]["ProblemDetails"];
          };
        };
        /** @description Authentication failed */
        401: {
          content: {
            "application/json": components["schemas"]["ProblemDetails"];
          };
        };
        /** @description Rate limit exceeded */
        429: {
          content: {
            "application/json": components["schemas"]["ProblemDetails"];
          };
        };
      };
    };
  };
  "/v1/logs/stream": {
    /** Subscribe to log stream via SSE */
    get: {
      responses: {
        /** @description SSE stream */
        200: {
          content: {
            "text/event-stream": string;
          };
        };
        /** @description Authentication failed */
        401: {
          content: {
            "application/json": components["schemas"]["ProblemDetails"];
          };
        };
        /** @description Rate limit exceeded */
        429: {
          content: {
            "application/json": components["schemas"]["ProblemDetails"];
          };
        };
        /** @description Log stream unavailable */
        503: {
          content: {
            "application/json": components["schemas"]["ProblemDetails"];
          };
        };
      };
    };
  };
  "/v1/torrents": {
    /** List torrents with pagination and filters */
    get: {
      parameters: {
        query?: {
          limit?: number;
          cursor?: string;
          state?: "queued" | "fetching_metadata" | "downloading" | "seeding" | "completed" | "failed" | "stopped";
          tracker?: string;
          extension?: string;
          /** @description Comma separated list of tags */
          tags?: string;
          name?: string;
        };
      };
      responses: {
        /** @description Torrent collection */
        200: {
          content: {
            "application/json": components["schemas"]["TorrentListResponse"];
          };
        };
        /** @description Invalid filters */
        400: {
          content: {
            "application/json": components["schemas"]["ProblemDetails"];
          };
        };
        /** @description Authentication failed */
        401: {
          content: {
            "application/json": components["schemas"]["ProblemDetails"];
          };
        };
        /** @description Rate limit exceeded */
        429: {
          content: {
            "application/json": components["schemas"]["ProblemDetails"];
          };
        };
        /** @description Torrent workflow unavailable */
        503: {
          content: {
            "application/json": components["schemas"]["ProblemDetails"];
          };
        };
      };
    };
    /** Submit a torrent descriptor to the engine */
    post: {
      requestBody: {
        content: {
          "application/json": components["schemas"]["TorrentCreateRequest"];
        };
      };
      responses: {
        /** @description Torrent accepted */
        202: {
          content: never;
        };
        /** @description Invalid submission */
        400: {
          content: {
            "application/json": components["schemas"]["ProblemDetails"];
          };
        };
        /** @description Authentication failed */
        401: {
          content: {
            "application/json": components["schemas"]["ProblemDetails"];
          };
        };
        /** @description Rate limit exceeded */
        429: {
          content: {
            "application/json": components["schemas"]["ProblemDetails"];
          };
        };
        /** @description Torrent workflow unavailable */
        503: {
          content: {
            "application/json": components["schemas"]["ProblemDetails"];
          };
        };
      };
    };
  };
  "/v1/torrents/categories": {
    /** List torrent categories */
    get: {
      responses: {
        /** @description Category list */
        200: {
          content: {
            "application/json": components["schemas"]["TorrentLabelEntry"][];
          };
        };
        /** @description Authentication failed */
        401: {
          content: {
            "application/json": components["schemas"]["ProblemDetails"];
          };
        };
        /** @description Rate limit exceeded */
        429: {
          content: {
            "application/json": components["schemas"]["ProblemDetails"];
          };
        };
        /** @description Torrent workflow unavailable */
        503: {
          content: {
            "application/json": components["schemas"]["ProblemDetails"];
          };
        };
      };
    };
  };
  "/v1/torrents/categories/{name}": {
    /** Create or update a torrent category */
    put: {
      parameters: {
        path: {
          name: string;
        };
      };
      requestBody: {
        content: {
          "application/json": components["schemas"]["TorrentLabelPolicy"];
        };
      };
      responses: {
        /** @description Category updated */
        200: {
          content: {
            "application/json": components["schemas"]["TorrentLabelEntry"];
          };
        };
        /** @description Invalid category payload */
        400: {
          content: {
            "application/json": components["schemas"]["ProblemDetails"];
          };
        };
        /** @description Authentication failed */
        401: {
          content: {
            "application/json": components["schemas"]["ProblemDetails"];
          };
        };
        /** @description Rate limit exceeded */
        429: {
          content: {
            "application/json": components["schemas"]["ProblemDetails"];
          };
        };
        /** @description Torrent workflow unavailable */
        503: {
          content: {
            "application/json": components["schemas"]["ProblemDetails"];
          };
        };
      };
    };
  };
  "/v1/torrents/create": {
    /** Author a new torrent from local files */
    post: {
      requestBody: {
        content: {
          "application/json": components["schemas"]["TorrentAuthorRequest"];
        };
      };
      responses: {
        /** @description Torrent authored */
        200: {
          content: {
            "application/json": components["schemas"]["TorrentAuthorResponse"];
          };
        };
        /** @description Invalid authoring request */
        400: {
          content: {
            "application/json": components["schemas"]["ProblemDetails"];
          };
        };
        /** @description Authentication failed */
        401: {
          content: {
            "application/json": components["schemas"]["ProblemDetails"];
          };
        };
        /** @description Rate limit exceeded */
        429: {
          content: {
            "application/json": components["schemas"]["ProblemDetails"];
          };
        };
        /** @description Torrent workflow unavailable */
        503: {
          content: {
            "application/json": components["schemas"]["ProblemDetails"];
          };
        };
      };
    };
  };
  "/v1/torrents/events": {
    /** Subscribe to torrent events via SSE */
    get: {
      parameters: {
        query?: {
          /** @description Comma separated torrent identifiers */
          torrent?: string;
          /** @description Comma separated event kinds */
          event?: string;
          /** @description Filter state change events by new state */
          state?: string;
        };
      };
      responses: {
        /** @description SSE stream */
        200: {
          content: {
            "text/event-stream": string;
          };
        };
        /** @description Authentication failed */
        401: {
          content: {
            "application/json": components["schemas"]["ProblemDetails"];
          };
        };
        /** @description Rate limit exceeded */
        429: {
          content: {
            "application/json": components["schemas"]["ProblemDetails"];
          };
        };
        /** @description Event stream unavailable */
        503: {
          content: {
            "application/json": components["schemas"]["ProblemDetails"];
          };
        };
      };
    };
  };
  "/v1/torrents/tags": {
    /** List torrent tags */
    get: {
      responses: {
        /** @description Tag list */
        200: {
          content: {
            "application/json": components["schemas"]["TorrentLabelEntry"][];
          };
        };
        /** @description Authentication failed */
        401: {
          content: {
            "application/json": components["schemas"]["ProblemDetails"];
          };
        };
        /** @description Rate limit exceeded */
        429: {
          content: {
            "application/json": components["schemas"]["ProblemDetails"];
          };
        };
        /** @description Torrent workflow unavailable */
        503: {
          content: {
            "application/json": components["schemas"]["ProblemDetails"];
          };
        };
      };
    };
  };
  "/v1/torrents/tags/{name}": {
    /** Create or update a torrent tag */
    put: {
      parameters: {
        path: {
          name: string;
        };
      };
      requestBody: {
        content: {
          "application/json": components["schemas"]["TorrentLabelPolicy"];
        };
      };
      responses: {
        /** @description Tag updated */
        200: {
          content: {
            "application/json": components["schemas"]["TorrentLabelEntry"];
          };
        };
        /** @description Invalid tag payload */
        400: {
          content: {
            "application/json": components["schemas"]["ProblemDetails"];
          };
        };
        /** @description Authentication failed */
        401: {
          content: {
            "application/json": components["schemas"]["ProblemDetails"];
          };
        };
        /** @description Rate limit exceeded */
        429: {
          content: {
            "application/json": components["schemas"]["ProblemDetails"];
          };
        };
        /** @description Torrent workflow unavailable */
        503: {
          content: {
            "application/json": components["schemas"]["ProblemDetails"];
          };
        };
      };
    };
  };
  "/v1/torrents/{id}": {
    /** Fetch torrent detail by identifier */
    get: {
      parameters: {
        path: {
          id: string;
        };
      };
      responses: {
        /** @description Torrent detail */
        200: {
          content: {
            "application/json": components["schemas"]["TorrentDetail"];
          };
        };
        /** @description Authentication failed */
        401: {
          content: {
            "application/json": components["schemas"]["ProblemDetails"];
          };
        };
        /** @description Torrent not found */
        404: {
          content: {
            "application/json": components["schemas"]["ProblemDetails"];
          };
        };
        /** @description Rate limit exceeded */
        429: {
          content: {
            "application/json": components["schemas"]["ProblemDetails"];
          };
        };
        /** @description Torrent workflow unavailable */
        503: {
          content: {
            "application/json": components["schemas"]["ProblemDetails"];
          };
        };
      };
    };
  };
  "/v1/torrents/{id}/action": {
    /** Trigger a torrent control action */
    post: {
      parameters: {
        path: {
          id: string;
        };
      };
      requestBody: {
        content: {
          "application/json": components["schemas"]["TorrentAction"];
        };
      };
      responses: {
        /** @description Action accepted */
        202: {
          content: never;
        };
        /** @description Invalid action payload */
        400: {
          content: {
            "application/json": components["schemas"]["ProblemDetails"];
          };
        };
        /** @description Authentication failed */
        401: {
          content: {
            "application/json": components["schemas"]["ProblemDetails"];
          };
        };
        /** @description Rate limit exceeded */
        429: {
          content: {
            "application/json": components["schemas"]["ProblemDetails"];
          };
        };
        /** @description Torrent workflow unavailable */
        503: {
          content: {
            "application/json": components["schemas"]["ProblemDetails"];
          };
        };
      };
    };
  };
  "/v1/torrents/{id}/options": {
    /** Update per-torrent options */
    patch: {
      parameters: {
        path: {
          id: string;
        };
      };
      requestBody: {
        content: {
          "application/json": components["schemas"]["TorrentOptionsRequest"];
        };
      };
      responses: {
        /** @description Options update accepted */
        202: {
          content: never;
        };
        /** @description Invalid option payload */
        400: {
          content: {
            "application/json": components["schemas"]["ProblemDetails"];
          };
        };
        /** @description Authentication failed */
        401: {
          content: {
            "application/json": components["schemas"]["ProblemDetails"];
          };
        };
        /** @description Rate limit exceeded */
        429: {
          content: {
            "application/json": components["schemas"]["ProblemDetails"];
          };
        };
        /** @description Torrent workflow unavailable */
        503: {
          content: {
            "application/json": components["schemas"]["ProblemDetails"];
          };
        };
      };
    };
  };
  "/v1/torrents/{id}/peers": {
    /** List torrent peers */
    get: {
      parameters: {
        path: {
          id: string;
        };
      };
      responses: {
        /** @description Peer list */
        200: {
          content: {
            "application/json": components["schemas"]["TorrentPeer"][];
          };
        };
        /** @description Authentication failed */
        401: {
          content: {
            "application/json": components["schemas"]["ProblemDetails"];
          };
        };
        /** @description Rate limit exceeded */
        429: {
          content: {
            "application/json": components["schemas"]["ProblemDetails"];
          };
        };
        /** @description Torrent workflow unavailable */
        503: {
          content: {
            "application/json": components["schemas"]["ProblemDetails"];
          };
        };
      };
    };
  };
  "/v1/torrents/{id}/select": {
    /** Update a torrent's file selection */
    post: {
      parameters: {
        path: {
          id: string;
        };
      };
      requestBody: {
        content: {
          "application/json": components["schemas"]["TorrentSelectionRequest"];
        };
      };
      responses: {
        /** @description Selection update accepted */
        202: {
          content: never;
        };
        /** @description Invalid selection payload */
        400: {
          content: {
            "application/json": components["schemas"]["ProblemDetails"];
          };
        };
        /** @description Authentication failed */
        401: {
          content: {
            "application/json": components["schemas"]["ProblemDetails"];
          };
        };
        /** @description Rate limit exceeded */
        429: {
          content: {
            "application/json": components["schemas"]["ProblemDetails"];
          };
        };
        /** @description Torrent workflow unavailable */
        503: {
          content: {
            "application/json": components["schemas"]["ProblemDetails"];
          };
        };
      };
    };
  };
  "/v1/torrents/{id}/trackers": {
    /** List torrent trackers */
    get: {
      parameters: {
        path: {
          id: string;
        };
      };
      responses: {
        /** @description Tracker list */
        200: {
          content: {
            "application/json": components["schemas"]["TorrentTrackersResponse"];
          };
        };
        /** @description Authentication failed */
        401: {
          content: {
            "application/json": components["schemas"]["ProblemDetails"];
          };
        };
        /** @description Rate limit exceeded */
        429: {
          content: {
            "application/json": components["schemas"]["ProblemDetails"];
          };
        };
        /** @description Torrent workflow unavailable */
        503: {
          content: {
            "application/json": components["schemas"]["ProblemDetails"];
          };
        };
      };
    };
    /** Remove torrent trackers */
    delete: {
      parameters: {
        path: {
          id: string;
        };
      };
      requestBody: {
        content: {
          "application/json": components["schemas"]["TorrentTrackersRemoveRequest"];
        };
      };
      responses: {
        /** @description Trackers removed */
        202: {
          content: never;
        };
        /** @description Invalid tracker removal */
        400: {
          content: {
            "application/json": components["schemas"]["ProblemDetails"];
          };
        };
        /** @description Authentication failed */
        401: {
          content: {
            "application/json": components["schemas"]["ProblemDetails"];
          };
        };
        /** @description Rate limit exceeded */
        429: {
          content: {
            "application/json": components["schemas"]["ProblemDetails"];
          };
        };
        /** @description Torrent workflow unavailable */
        503: {
          content: {
            "application/json": components["schemas"]["ProblemDetails"];
          };
        };
      };
    };
    /** Update torrent trackers */
    patch: {
      parameters: {
        path: {
          id: string;
        };
      };
      requestBody: {
        content: {
          "application/json": components["schemas"]["TorrentTrackersRequest"];
        };
      };
      responses: {
        /** @description Trackers updated */
        202: {
          content: never;
        };
        /** @description Invalid tracker update */
        400: {
          content: {
            "application/json": components["schemas"]["ProblemDetails"];
          };
        };
        /** @description Authentication failed */
        401: {
          content: {
            "application/json": components["schemas"]["ProblemDetails"];
          };
        };
        /** @description Rate limit exceeded */
        429: {
          content: {
            "application/json": components["schemas"]["ProblemDetails"];
          };
        };
        /** @description Torrent workflow unavailable */
        503: {
          content: {
            "application/json": components["schemas"]["ProblemDetails"];
          };
        };
      };
    };
  };
  "/v1/torrents/{id}/web_seeds": {
    /** Update torrent web seeds */
    patch: {
      parameters: {
        path: {
          id: string;
        };
      };
      requestBody: {
        content: {
          "application/json": components["schemas"]["TorrentWebSeedsRequest"];
        };
      };
      responses: {
        /** @description Web seeds updated */
        202: {
          content: never;
        };
        /** @description Invalid web seed update */
        400: {
          content: {
            "application/json": components["schemas"]["ProblemDetails"];
          };
        };
        /** @description Authentication failed */
        401: {
          content: {
            "application/json": components["schemas"]["ProblemDetails"];
          };
        };
        /** @description Rate limit exceeded */
        429: {
          content: {
            "application/json": components["schemas"]["ProblemDetails"];
          };
        };
        /** @description Torrent workflow unavailable */
        503: {
          content: {
            "application/json": components["schemas"]["ProblemDetails"];
          };
        };
      };
    };
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    ApiKeyRefreshResponse: {
      api_key_expires_at: string;
    };
    ConfigSnapshot: {
      app_profile: Record<string, never>;
      engine_profile: Record<string, never>;
      engine_profile_effective: Record<string, never>;
      fs_policy: Record<string, never>;
      /** Format: int64 */
      revision: number;
    };
    DashboardResponse: {
      /** Format: int32 */
      active: number;
      /** Format: int32 */
      completed: number;
      /** Format: int32 */
      disk_total_gb: number;
      /** Format: int32 */
      disk_used_gb: number;
      /** Format: int64 */
      download_bps: number;
      /** Format: int32 */
      paused: number;
      /** Format: int64 */
      upload_bps: number;
    };
    FactoryResetRequest: {
      confirm: string;
    };
    FilePriorityOverride: {
      /** Format: int32 */
      index: number;
      /** @enum {string} */
      priority: "skip" | "low" | "normal" | "high";
    };
    FsBrowseResponse: {
      entries: components["schemas"]["FsEntry"][];
      parent?: string;
      path: string;
    };
    FsEntry: {
      kind: components["schemas"]["FsEntryKind"];
      name: string;
      path: string;
    };
    /** @enum {string} */
    FsEntryKind: "directory" | "file" | "symlink" | "other";
    FullHealthResponse: {
      build: string;
      degraded: string[];
      metrics: components["schemas"]["HealthMetricsResponse"];
      mode: string;
      /** Format: int64 */
      revision: number;
      status: string;
      torrent: components["schemas"]["TorrentHealthSnapshot"];
    };
    HealthComponent: {
      /** Format: int64 */
      revision?: number;
      status: string;
    };
    HealthMetricsResponse: {
      /** Format: int64 */
      config_apply_latency_ms: number;
      /** Format: int64 */
      config_update_failures_total: number;
      /** Format: int64 */
      config_watch_latency_ms: number;
      /** Format: int64 */
      config_watch_slow_total: number;
      /** Format: int64 */
      guardrail_violations_total: number;
      /** Format: int64 */
      rate_limit_throttled_total: number;
    };
    HealthResponse: {
      database: components["schemas"]["HealthComponent"];
      mode: string;
      status: string;
    };
    PeerChoke: {
      local: boolean;
      remote: boolean;
    };
    PeerInterest: {
      local: boolean;
      remote: boolean;
    };
    ProblemDetails: {
      detail?: string;
      status: number;
      title: string;
      type: string;
    };
    SettingsChangeset: {
      api_keys?: Record<string, never>[];
      app_profile?: Record<string, never> | null;
      engine_profile?: Record<string, never> | null;
      fs_policy?: Record<string, never> | null;
      secrets?: Record<string, never>[];
    };
    SetupCompleteResponse: {
      api_key?: string;
      /** Format: date-time */
      api_key_expires_at?: string;
      snapshot: components["schemas"]["ConfigSnapshot"];
    };
    SetupStartRequest: {
      issued_by?: string;
      /** Format: int64 */
      ttl_seconds?: number;
    };
    SetupStartResponse: {
      /** Format: date-time */
      expires_at: string;
      token: string;
    };
    /** @enum {string} */
    StorageMode: "sparse" | "allocate";
    TorrentAction: {
      delete_data?: boolean | null;
      /** Format: int64 */
      download_bps?: number | null;
      enable?: boolean | null;
      /** @enum {string} */
      type: "pause" | "resume" | "remove" | "reannounce" | "recheck" | "sequential" | "rate";
      /** Format: int64 */
      upload_bps?: number | null;
    };
    TorrentAuthorFileView: {
      path: string;
      /** Format: int64 */
      size_bytes: number;
    };
    TorrentAuthorRequest: {
      comment?: string | null;
      exclude?: string[];
      include?: string[];
      /** Format: int32 */
      piece_length?: number | null;
      private?: boolean;
      root_path: string;
      skip_fluff?: boolean;
      source?: string | null;
      trackers?: string[];
      web_seeds?: string[];
    };
    TorrentAuthorResponse: {
      comment?: string | null;
      files: components["schemas"]["TorrentAuthorFileView"][];
      info_hash: string;
      magnet_uri: string;
      /** Format: byte */
      metainfo: string;
      /** Format: int32 */
      piece_length: number;
      private: boolean;
      source?: string | null;
      /** Format: int64 */
      total_size: number;
      trackers: string[];
      warnings: string[];
      web_seeds: string[];
    };
    TorrentCleanupPolicy: {
      remove_data: boolean;
      /** Format: float */
      seed_ratio_limit?: number | null;
      /** Format: int64 */
      seed_time_limit?: number | null;
    };
    TorrentCreateRequest: {
      auto_managed?: boolean | null;
      category?: string | null;
      comment?: string | null;
      download_dir?: string | null;
      exclude?: string[];
      /** Format: int32 */
      hash_check_sample_pct?: number | null;
      /** Format: uuid */
      id: string;
      include?: string[];
      magnet?: string | null;
      /** Format: int32 */
      max_connections?: number | null;
      /** Format: int64 */
      max_download_bps?: number | null;
      /** Format: int64 */
      max_upload_bps?: number | null;
      /** Format: byte */
      metainfo?: string | null;
      name?: string | null;
      pex_enabled?: boolean | null;
      private?: boolean | null;
      /** Format: int32 */
      queue_position?: number | null;
      replace_trackers?: boolean;
      replace_web_seeds?: boolean;
      seed_mode?: boolean | null;
      /** Format: float */
      seed_ratio_limit?: number | null;
      /** Format: int64 */
      seed_time_limit?: number | null;
      sequential?: boolean | null;
      skip_fluff?: boolean;
      source?: string | null;
      start_paused?: boolean | null;
      storage_mode?: components["schemas"]["StorageMode"] | null;
      super_seeding?: boolean | null;
      tags?: string[];
      trackers?: string[];
      web_seeds?: string[];
    };
    TorrentDetail: {
      files?: components["schemas"]["TorrentFileView"][] | null;
      settings?: components["schemas"]["TorrentSettingsView"] | null;
      summary: components["schemas"]["TorrentSummary"];
    };
    TorrentFileView: {
      /** Format: int64 */
      bytes_completed: number;
      /** Format: int32 */
      index: number;
      path: string;
      /** @enum {string} */
      priority: "skip" | "low" | "normal" | "high";
      selected: boolean;
      /** Format: int64 */
      size_bytes: number;
    };
    TorrentHealthSnapshot: {
      /** Format: int64 */
      active: number;
      /** Format: int64 */
      queue_depth: number;
    };
    TorrentLabelEntry: {
      name: string;
      policy: components["schemas"]["TorrentLabelPolicy"];
    };
    TorrentLabelPolicy: {
      auto_managed?: boolean | null;
      cleanup?: components["schemas"]["TorrentCleanupPolicy"] | null;
      download_dir?: string | null;
      /** Format: int32 */
      queue_position?: number | null;
      rate_limit?: components["schemas"]["TorrentRateLimit"] | null;
      /** Format: float */
      seed_ratio_limit?: number | null;
      /** Format: int64 */
      seed_time_limit?: number | null;
    };
    TorrentListResponse: {
      next?: string | null;
      torrents: components["schemas"]["TorrentSummary"][];
    };
    TorrentOptionsRequest: {
      auto_managed?: boolean | null;
      comment?: string | null;
      /** Format: int32 */
      connections_limit?: number | null;
      paused?: boolean | null;
      pex_enabled?: boolean | null;
      private?: boolean | null;
      /** Format: int32 */
      queue_position?: number | null;
      /** Format: float */
      seed_ratio_limit?: number | null;
      /** Format: int64 */
      seed_time_limit?: number | null;
      source?: string | null;
      super_seeding?: boolean | null;
    };
    TorrentPeer: {
      choke: components["schemas"]["PeerChoke"];
      client?: string;
      /** Format: int64 */
      download_bps: number;
      endpoint: string;
      interest: components["schemas"]["PeerInterest"];
      progress: number;
      /** Format: int64 */
      upload_bps: number;
    };
    TorrentProgressView: {
      /** Format: int64 */
      bytes_downloaded: number;
      /** Format: int64 */
      bytes_total: number;
      /** Format: int64 */
      eta_seconds?: number | null;
      /** Format: float */
      percent_complete: number;
    };
    TorrentRateLimit: {
      /** Format: int64 */
      download_bps?: number | null;
      /** Format: int64 */
      upload_bps?: number | null;
    };
    TorrentRatesView: {
      /** Format: int64 */
      download_bps: number;
      /** Format: float */
      ratio: number;
      /** Format: int64 */
      upload_bps: number;
    };
    TorrentSelectionRequest: {
      exclude?: string[];
      include?: string[];
      priorities?: components["schemas"]["FilePriorityOverride"][];
      skip_fluff?: boolean;
    };
    TorrentSelectionView: {
      exclude: string[];
      include: string[];
      priorities?: components["schemas"]["FilePriorityOverride"][];
      skip_fluff: boolean;
    };
    TorrentSettingsView: {
      auto_managed?: boolean | null;
      category?: string | null;
      cleanup?: components["schemas"]["TorrentCleanupPolicy"] | null;
      comment?: string | null;
      /** Format: int32 */
      connections_limit?: number | null;
      download_dir?: string | null;
      pex_enabled?: boolean | null;
      private?: boolean | null;
      /** Format: int32 */
      queue_position?: number | null;
      rate_limit?: components["schemas"]["TorrentRateLimit"] | null;
      seed_mode?: boolean | null;
      /** Format: float */
      seed_ratio_limit?: number | null;
      /** Format: int64 */
      seed_time_limit?: number | null;
      selection?: components["schemas"]["TorrentSelectionView"] | null;
      sequential: boolean;
      source?: string | null;
      storage_mode?: components["schemas"]["StorageMode"] | null;
      super_seeding?: boolean | null;
      tags: string[];
      tracker_messages?: {
        [key: string]: string;
      };
      trackers: string[];
      use_partfile?: boolean | null;
      web_seeds?: string[];
    };
    TorrentStateView: {
      failure_message?: string | null;
      /** @enum {string} */
      kind: "queued" | "fetching_metadata" | "downloading" | "seeding" | "completed" | "failed" | "stopped";
    };
    TorrentSummary: {
      /** Format: date-time */
      added_at: string;
      category?: string | null;
      /** Format: date-time */
      completed_at?: string | null;
      /** Format: int32 */
      connections_limit?: number | null;
      download_dir?: string | null;
      /** Format: uuid */
      id: string;
      /** Format: date-time */
      last_updated: string;
      library_path?: string | null;
      name?: string | null;
      progress: components["schemas"]["TorrentProgressView"];
      rate_limit?: components["schemas"]["TorrentRateLimit"] | null;
      rates: components["schemas"]["TorrentRatesView"];
      sequential: boolean;
      state: components["schemas"]["TorrentStateView"];
      tags: string[];
      trackers: string[];
    };
    TorrentTrackersRemoveRequest: {
      trackers?: string[];
    };
    TorrentTrackersRequest: {
      replace?: boolean;
      trackers?: string[];
    };
    TorrentTrackersResponse: {
      trackers: components["schemas"]["TrackerView"][];
    };
    TorrentWebSeedsRequest: {
      replace?: boolean;
      web_seeds?: string[];
    };
    TrackerView: {
      message?: string;
      status?: string;
      url: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export type operations = Record<string, never>;
